### ISSUE TITLE
Images no longer resize on upload - Craft 3.2.4, ImageResize 2.0.5

### ISSUE THREAD

**Issue by peter-tell** [engram-design/ImageResizer#53] opened 2019-07-18 14:27 UTC
### Description
Uploading an image no longer triggers the image to resize

### Steps to reproduce

1. Upload an Image

### Additional info

- Plugin version: 2.0.5
- Craft version: 3.2.4

**Comment by mark-chief** [comment] 2019-08-14 12:16
This get resolved?

**Comment by peter-tell** [comment] 2019-08-15 18:42
@mark-chief  Not to my knowledge

**Comment by karan-saluja** [comment] 2019-09-13 13:53
@peter-tell @mark-chief 

I gave it a try. Commenting lines 37-39 of file src/services/Service.php solves this issue. Don't know if there are any side effects of doing this

**Comment by engram-design** [comment] 2019-09-18 11:03
Reason for the lack of fix, is that I can't reproduce it! Do any of you have extra fields on your assets that might cause validation to fail? I'm also now testing on 3.3.x

**Comment by karan-saluja** [comment] 2019-09-18 11:25
No, I have no additional fields on my assets. I'm attaching my projects composer file, also adding screenshots of plugin settings and asset settings
<img width="971" alt="Screenshot 2019-09-18 at 4 54 36 PM" src="https://user-images.githubusercontent.com/28668444/65144485-17448880-da35-11e9-8de6-b6ca61bf5b10.png">
<img width="660" alt="Screenshot 2019-09-18 at 4 55 05 PM" src="https://user-images.githubusercontent.com/28668444/65144488-17dd1f00-da35-11e9-98c6-16a0a8c3a95c.png">

{
  "require": {
    "craftcms/cms": "3.3.4",
    "craftcms/redactor": "2.4.0",
    "ether/seo": "3.6.2",
    "putyourlightson/craft-campaign": "1.11.1",
    "verbb/image-resizer": "2.0.5",
    "verbb/super-table": "2.3.0",
    "vlucas/phpdotenv": "^2.4.0"
  },
  "autoload": {
    "psr-4": {
      "modules\\": "modules/"
    }
  },
  "config": {
    "sort-packages": true,
    "optimize-autoloader": true,
    "platform": {
      "php": "7.0"
    }
  },
  "scripts": {
    "post-root-package-install": [
      "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
    ]
  }
}

**Comment by engram-design** [comment] 2019-09-18 11:41
Thanks for the issue. Is there any information in the logs after testing the upload?

Looking into removing the line as you've mentioned, but it was there for a reason (assets can be processed twice in some instances)

**Comment by karan-saluja** [comment] 2019-09-18 11:44
No, there are no new logs.
Maybe try uploading an image, then delete it, then adding it again?

**Comment by engram-design** [comment] 2019-09-18 12:19
Should be fixed in [2.0.6](https://github.com/verbb/image-resizer/releases/tag/2.0.6).

**Closed as completed by engram-design** 2019-09-18 12:19 UTC

**Comment by karan-saluja** [comment] 2019-09-18 12:43
@engram-design Thanks a lot :)
