### ISSUE TITLE
Image-resizer never resizes an image

### ISSUE THREAD

**Issue by jamie-s-white** [engram-design/ImageResizer#80] opened 2023-09-12 14:13 UTC
### Describe the bug

Image-resizer never resizes an image

### Steps to reproduce

1. Upload any image
2. In logs we get "Resizing would result in a larger file size."
3. We then downgrade from image-resizer 2.2.1 to 2.1.0
4. Upload the same image
5. In the logs we get "Resized successfully. Saved 41% (2.35mb)." (and we can see the image has correctly reduced file size and dimensions - test-image-j.jpg and testing-2-1-0.jpg are the same file, just renamed):
<img width="1027" alt="Screenshot 2023-09-12 at 15 12 17" src="https://github.com/verbb/image-resizer/assets/137078049/f85767f7-ffed-4bd3-bf15-715faa9b9950">

### Craft CMS version

3.7.16

### Plugin version

2.2.1

### Multi-site?

No

**Comment by engram-design** [comment] 2023-09-13 07:46
Probably related to the changed behaviour [here](https://github.com/verbb/image-resizer/commit/1114067baf166c33b372a992f6ca478cd1d95a46) which was supposed to drastically improve performance when resizing images. I would have suspected this could mean results were a _little_ bit off, due to using in-memory images and estimating the size that way, but a 2.35mb difference is quite off.

**Comment by engram-design** [comment] 2023-09-13 10:36
So I've tried a number of different images to test, and not able to reproduce this one. Are you able to advise your Image Resizer settings, the method you're using to upload (via Assets directly, via an Assets field on an entry, bulk resize element action, etc), and send the image you're using to `support@verbb.io`?

**Comment by jamie-s-white** [comment] 2023-09-13 11:00
Our resizer settings are default, this was a fresh install
We uploaded the assets directly
Will send image

**Comment by engram-design** [comment] 2023-09-13 12:17
Thanks for sending that through. So on my end, that's uploading and resizing correctly.

<img width="715" alt="image" src="https://github.com/verbb/image-resizer/assets/1221575/9869bd04-d835-40f4-beeb-154b098c20d6">

<img width="711" alt="image" src="https://github.com/verbb/image-resizer/assets/1221575/2cd18a7c-1986-462e-9566-ac50d6df7e36">

Are you able to confirm if your project uses ImageMagick or GD for image handling? Easiest way to determine this is in Utilities > PHP Info. There's also a Craft setting to control this - https://craftcms.com/docs/4.x/config/general.html#imagedriver

**Comment by jamie-s-white** [comment] 2023-09-13 12:33
Imagick 3.7.0 (ImageMagick 6.9.10-23)

**Comment by engram-design** [comment] 2023-09-13 12:36
Imagick 3.5.1 here, I don't _think_ that's going to make a massive difference. It was more if you were using GD vs Imagick. I'm also testing with both local an S3 volumes just in case. Strange.

**Comment by jamie-s-white** [comment] 2023-09-14 10:13
Very strange!

As we are using an older version of Craft, and you are unable to replicate, I'm not sure if I will now pursue this bug. My main concern was that there were more fundamental issues with the update which you should be aware of, which there clearly aren't, and it seems there is something specific with our set up.

We are happy using the older version of the plugin without the performance improvements for this client, and I will be mindful if we see this issue again in the future when everything is up to date.

Thank you very much for the work you've put into this ticket.

**Comment by engram-design** [comment] 2023-09-14 12:58
I'll continue investigating, and especially if anyone else has similar issues (no one has yet to report it).

**Comment by jamie-s-white** [comment] 2023-09-14 13:21
OK! We can't right now, because we are getting client approval on our staging site with the older version, however, if you want some further debug information from our staging environment (for example, the two file sizes it is trying to compare) then I could look to add the lines of debug to the plugin and then send you the resulting log file?

I do now also wonder if it is related to the other ticket I raised:

https://github.com/verbb/image-resizer/issues/79

And if the file size of the original image is always 0, because it is not properly finding it and getting its size, and then it compares it to the new size, which is always greater than 0. (This is purely a hunch, I have not investigated this at all!)

**Comment by jamie-s-white** [comment] 2023-09-14 13:48
I've done a further bit of digging myself (because I couldn't get this out of my head until I had pulled this thread):

With 2.1.1:

if (filesize($tempPath) < filesize($path)) {
// filesize($tempPath) =  3516406
// filesize($path) = 6534207

With 2.2.1:

$resizedSize = strlen((string)$image->getImagineImage()->get('jpg')) * 10;
// Lets check to see if this resize resulted in a larger file - revert if so.
if ($resizedSize < filesize($path)) {
// filesize($tempPath) =  3516406
// filesize($path) = 6534207
// $resizedSize = 35164060

I notice you have *10 at the end of this function @engram-design, and I'm not sure why... And why this would work on other systems but not ours. But that is clearly what is going on here. 

Hope this helps :)

**Comment by engram-design** [comment] 2023-09-14 22:18
Thanks for investigating! So for some background, it's incredibly more performant to get the resized image in-memory using `$image->getImagineImage()->get('jpg')` rather than saving it to the filesystem to just determine how large the file is going to be. There's no other method that I'm aware of to be able to determine if the file is going to be a larger filesize than to actually make it a file, or this approach.

So `$image->getImagineImage()->get('jpg')` will produce the raw representation of the image, and we use `strlen` to get the size of that. Multiplying that by 10 was getting closer results for me, but that's indeed off now for me also. I'm not _quite_ sure why it's not an issue for me, but going to chalk it up to the estimation factor here.

I've since refined that through some more testing to get more accurate results. Keen to see if that's the same on your end?

To get this early, run `composer require verbb/image-resizer:"dev-craft-3 as 2.2.1"`.

**Comment by jamie-s-white** [comment] 2023-09-18 12:50
We have tested this in our staging environment, and this is working on all assets we have tested this on, thank you!

**Comment by jamie-s-white** [comment] 2023-10-09 13:55
Hi,

This is still on the dev branch at the moment. We would like to upgrade to it when it is officially released so that we can resize new image uploads automatically. Do you know what sort of time frame this will be?

Thank you!

**Comment by engram-design** [comment] 2023-10-09 22:06
Fixed in [2.2.2](https://github.com/verbb/image-resizer/releases/tag/2.2.2)

**Closed as completed by engram-design** 2023-10-09 22:06 UTC
